apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sleep
    service: sleep
  name: sleep
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - command:
            - /bin/sleep
            - infinity
          image: docker.io/curlimages/curl:8.16.0
          imagePullPolicy: IfNotPresent
          name: sleep
          volumeMounts:
            - mountPath: /etc/sleep/tls
              name: secret-volume
      serviceAccountName: sleep
      terminationGracePeriodSeconds: 0
      volumes:
        - name: secret-volume
          secret:
            optional: true
            secretName: sleep-secret
