apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortio
    service: fortio
  name: fortio
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: fortio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      annotations:
        proxy.istio.io/config: "proxyStatsMatcher:\n  inclusionPrefixes:\n  - \"cluster.outbound\"\
          \n  - \"cluster_manager\"\n  - \"listener_manager\"\n  - \"server\"\n  -\
          \ \"cluster.xds-grpc\""
      labels:
        app: fortio
    spec:
      containers:
        - image: docker.io/fortio/fortio:latest_release
          imagePullPolicy: Always
          name: fortio
          ports:
            - containerPort: 8080
              name: http-fortio
            - containerPort: 8079
              name: grpc-ping
