apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: istio-cni
  namespace: argocd
spec:
  destination:
    name: ambient-cluster
    namespace: kube-system
  project: default
  sources:
    - chart: cni
      helm:
        valueFiles:
          - $values/manifests/charts/istio-cni/ambient-values.yaml
        valuesObject:
          cni:
            cniBinDir: /home/kubernetes/bin
          revision: rapid
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.18.5
    - ref: values
      repoURL: https://github.com/istio/istio.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
