apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: istio-addons
  namespace: argocd
spec:
  destination:
    name: ambient-cluster
    namespace: istio-system
  project: default
  source:
    directory:
      exclude: loki.yaml
    path: samples/addons
    repoURL: https://github.com/istio/istio.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
