apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: istio-tags
  namespace: argocd
spec:
  destination:
    name: ambient-cluster
    namespace: istio-system
  project: default
  source:
    helm:
      valuesObject:
        base:
          istiodservice: 1-18-5
          tags:
            default:
              revision: 1-18-5
            rapid:
              revision: 1-19-3
            stable:
              revision: 1-18-5
    path: tag-chart
    repoURL: '{repo-placeholder}'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
