apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: enable-istio-coredumps
  name: enable-istio-coredumps
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: enable-istio-coredumps
  template:
    metadata:
      labels:
        app: enable-istio-coredumps
    spec:
      containers:
        - args:
            - -f
            - /dev/null
          command:
            - tail
          image: docker.io/library/alpine
          name: sleepforever
          resources:
            requests:
              cpu: 1m
      hostNetwork: true
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w kernel.core_pattern=/var/lib/istio/data/core.proxy && ulimit
              -c unlimited
          image: docker.io/library/alpine
          imagePullPolicy: IfNotPresent
          name: setsysctls
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /sys
              name: sys
      volumes:
        - hostPath:
            path: /sys
          name: sys
