apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: meta-application
spec:
  destination:
    name: in-cluster
    namespace: argocd
    server: ''
  project: default
  sources:
    - path: istio
      repoURL: '{repo-placeholder}'
      targetRevision: HEAD
    - directory:
        include: application.yaml
      path: application
      repoURL: '{repo-placeholder}'
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
