apiVersion: v1
kind: Service
metadata:
  labels:
    app: liveness
    service: liveness
  name: liveness
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: liveness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness
spec:
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 3600
          image: registry.k8s.io/busybox
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          name: liveness
