apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: make-aptget-work
spec:
  hosts:
    - deb.debian.org
    - cdn-fastly.deb.debian.org
    - security.debian.org
    - archive.ubuntu.com
    - security.ubuntu.com
  ports:
    - name: http
      number: 80
      protocol: HTTP
