apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: python-https
spec:
  hosts:
    - pypi.python.org
  ports:
    - name: https
      number: 443
      protocol: HTTPS
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: pypi-https
spec:
  hosts:
    - pypi.org
  ports:
    - name: https
      number: 443
      protocol: HTTPS
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: pythonhosted-https
spec:
  hosts:
    - files.pythonhosted.org
  ports:
    - name: https
      number: 443
      protocol: HTTPS
