apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sleep
    service: sleep
  name: sleep
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      annotations:
        inject.istio.io/templates: sidecar,spire
      labels:
        app: sleep
        spiffe.io/spire-managed-identity: 'true'
    spec:
      containers:
        - command:
            - /bin/sleep
            - infinity
          image: docker.io/curlimages/curl:8.16.0
          imagePullPolicy: IfNotPresent
          name: sleep
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      serviceAccountName: sleep
      terminationGracePeriodSeconds: 0
      volumes:
        - emptyDir: {}
          name: tmp
