apiVersion: v1
kind: Service
metadata:
  name: reviews-v1
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: reviews
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-v2
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: reviews
    version: v2
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-v3
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: reviews
    version: v3
---
apiVersion: v1
kind: Service
metadata:
  name: productpage-v1
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: productpage
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: ratings-v1
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: ratings
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: details-v1
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: details
    version: v1
