apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
  name: jaeger
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      annotations:
        prometheus.io/port: '8888'
        prometheus.io/scrape: 'true'
      labels:
        app: jaeger
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - args:
            - --config
            - /jaeger-configuration/config.yaml
          image: docker.io/jaegertracing/jaeger:2.14.0
          livenessProbe:
            httpGet:
              path: /status
              port: 13133
          name: jaeger
          readinessProbe:
            httpGet:
              path: /status
              port: 13133
          resources:
            requests:
              cpu: 10m
          volumeMounts:
            - mountPath: /badger
              name: data
            - mountPath: /jaeger-configuration
              name: jaeger-configuration
      volumes:
        - emptyDir: {}
          name: data
        - configMap:
            name: jaeger
          name: jaeger-configuration
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: tracing
  namespace: istio-system
spec:
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 16686
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: v1
data:
  config.yaml: "service:\n  extensions: [jaeger_storage, jaeger_query, remote_sampling,\
    \ healthcheckv2, expvar, zpages]\n  pipelines:\n    traces:\n      receivers:\
    \ [otlp, jaeger, zipkin]\n      processors: [batch]\n      exporters: [jaeger_storage_exporter]\n\
    \  telemetry:\n    resource:\n      service.name: jaeger\n    metrics:\n     \
    \ level: detailed\n      readers:\n        - pull:\n            exporter:\n  \
    \            prometheus:\n                host: \"0.0.0.0\"\n                port:\
    \ 8888\n    logs:\n      level: info\n    # TODO Initialize telemetry tracer once\
    \ OTEL released new feature.\n    # https://github.com/open-telemetry/opentelemetry-collector/issues/10663\n\
    \nextensions:\n  jaeger_query:\n    base_path: /jaeger\n    storage:\n      traces:\
    \ badger_storage\n\n  jaeger_storage:\n    backends:\n      badger_storage:\n\
    \        badger:\n          ephemeral: false\n          directories:\n       \
    \     keys: \"/badger/key\"\n            values: \"/badger/data/\"\n\n  remote_sampling:\n\
    \    # We can either use file or adaptive sampling strategy in remote_sampling\n\
    \    file:\n      path:\n      default_sampling_probability: 1\n      reload_interval:\
    \ 1s\n    # adaptive:\n    #   sampling_store: some_store\n    #   initial_sampling_probability:\
    \ 0.1\n    http:\n      endpoint: \"0.0.0.0:5778\"\n    grpc:\n      endpoint:\
    \ \"0.0.0.0:5779\"\n\n  healthcheckv2:\n    use_v2: true\n    http:\n      endpoint:\
    \ \"0.0.0.0:13133\"\n    grpc:\n\n  expvar:\n    endpoint: \"0.0.0.0:27777\"\n\
    \n  zpages:\n    # for some reason the official extension listens on ephemeral\
    \ port 55679\n    # so we override it with a normal port\n    endpoint: \"0.0.0.0:27778\"\
    \n\nreceivers:\n  otlp:\n    protocols:\n      grpc:\n        endpoint: \"0.0.0.0:4317\"\
    \n      http:\n        endpoint: \"0.0.0.0:4318\"\n\n  jaeger:\n    protocols:\n\
    \      grpc:\n        endpoint: \"0.0.0.0:14250\"\n      thrift_http:\n      \
    \  endpoint: \"0.0.0.0:14268\"\n      thrift_binary:\n        endpoint: \"0.0.0.0:6832\"\
    \n      thrift_compact:\n        endpoint: \"0.0.0.0:6831\"\n\n  zipkin:\n   \
    \ endpoint: \"0.0.0.0:9411\"\n\nprocessors:\n  batch:\n\nexporters:\n  jaeger_storage_exporter:\n\
    \    trace_storage: badger_storage\n"
kind: ConfigMap
metadata:
  labels:
    app: jaeger
  name: jaeger
  namespace: istio-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
  namespace: istio-system
spec:
  ports:
    - name: http-query
      port: 9411
      targetPort: 9411
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger-collector
  namespace: istio-system
spec:
  ports:
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: http-zipkin
      port: 9411
      targetPort: 9411
    - name: grpc-otel
      port: 4317
    - name: http-otel
      port: 4318
  selector:
    app: jaeger
  type: ClusterIP
