apiVersion: v1
kind: Service
metadata:
  labels:
    app: tcp-echo
    service: tcp-echo
  name: tcp-echo
spec:
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 9000
    - name: tcp-other
      port: 9001
  selector:
    app: tcp-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
      version: v1
  template:
    metadata:
      labels:
        app: tcp-echo
        version: v1
    spec:
      containers:
        - args:
            - 9000,9001,9002
            - hello
          image: registry.istio.io/release/tcp-echo-server:1.3
          imagePullPolicy: IfNotPresent
          name: tcp-echo
          ports:
            - containerPort: 9000
            - containerPort: 9001
