apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: tcp-echo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: tcp
        number: 31400
        protocol: TCP
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: tcp-echo-destination
spec:
  host: tcp-echo
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: tcp-echo
spec:
  gateways:
    - tcp-echo-gateway
  hosts:
    - '*'
  tcp:
    - match:
        - port: 31400
      route:
        - destination:
            host: tcp-echo
            port:
              number: 9000
            subset: v1
