apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: details
    version: v2
  name: details-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v2
  template:
    metadata:
      labels:
        app: details
        version: v2
    spec:
      containers:
        - env:
            - name: DO_NOT_ENCRYPT
              value: 'true'
          image: registry.istio.io/release/examples-bookinfo-details-v2:1.20.3
          imagePullPolicy: IfNotPresent
          name: details
          ports:
            - containerPort: 9080
